# Generated by Django 5.1.4 on 2024-12-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='age',
            new_name='amount',
        ),
    ]
