# Generated by Django 5.1.4 on 2024-12-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_ingredient_rename_age_ingredient_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('taste', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('prep_time', models.IntegerField()),
            ],
        ),
    ]
